//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by QuickQuiz.rc
//
#define IDD_ABOUTBOX                    100
#define ID_VIEW_ARRANGE                 127
#define IDR_MAINFRAME                   128
#define IDR_EDITMENU                    129
#define IDR_LISTMENU                    130
#define IDR_SHOWMENU                    131
#define IDB_LVIEWICON                   140
#define IDB_QVIEWICON                   141
#define IDB_STOREICON                   142
#define IDD_EDIT_DLG                    161
#define IDD_CHILD_SCHOISE_DLG           162
#define IDD_CHILD_MCHOISE_DLG           163
#define IDD_CHILD_JUDGE_DLG             164
#define IDD_CHILD_BLANK_DLG             165
#define IDD_CHILD_TEXT_DLG              166
#define IDD_ALLBUILD_DLG                167
#define IDD_OPENDOC_DLG                 168
#define IDD_CODE_DLG                    169
#define IDD_ITEMPROP_DLG                170
#define IDD_PAPERPROP_DLG               171
#define IDD_TYPEPROP_DLG                172
#define IDD_TESTSET_COMMDLG             173
#define IDD_TESTSET_CHSDLG              174
#define IDD_TESTSET_BLKTXTDLG           175
#define IDD_BLKTXTCHECK_DLG             176
#define IDD_VIEW_DLG                    177
#define IDD_CHOOSETYPE_DLG              178
#define IDD_TESTCOMP_DLG                179
#define IDD_TESTSET_DLG                 180
#define IDD_ADDTYPE_DLG                 181
#define IDD_PASSWORD_DLG                182
#define IDD_UNLOCK_DLG                  183
#define IDD_ITEMGROUP_DLG               184
#define IDD_SUMMARYLEN_DLG              185
#define IDD_BATCHSET_DLG                186
#define IDD_JPEGCOVER_DLG               187
#define IDD_IMAGESET_BAR                188
#define IDD_TEST_BAR                    189
#define IDD_TXTOUT_DLG                  190
#define IDD_COPYEX_DLG                  191
#define IDC_EDIT_DESC                   1000
#define IDC_BUTTON_DESC                 1001
#define IDC_BUTTON_SETDESCIMAGE         1002
#define IDC_TAB_TYPE                    1003
#define IDC_BUTTON_PRE                  1004
#define IDC_BUTTON_NEXT                 1005
#define IDC_BUTTON_NEW                  1006
#define IDC_BUTTON_DEL                  1007
#define IDC_BUTTON_ALLBUILD             1008
#define IDC_BUTTON_TEXT                 1009
#define IDC_STATIC_EDITINFO             1010
#define IDC_CHECK_TOPMOST               1011
#define IDC_STATIC_GROUP1               1012
#define IDC_BUTTON_OK                   1013
#define IDC_EDIT_RESOLVE                1014
#define IDC_BUTTON_RESOLVE              1015
#define IDC_BUTTON_STORE                1016
#define IDC_BUTTON_SETRESIMAGE          1017
#define IDC_CHECK_ANSWER1               1020
#define IDC_CHECK_ANSWER2               1021
#define IDC_CHECK_ANSWER3               1022
#define IDC_CHECK_ANSWER4               1023
#define IDC_CHECK_ANSWER5               1024
#define IDC_CHECK_ANSWER6               1025
#define IDC_CHECK_ANSWER7               1026
#define IDC_CHECK_ANSWER8               1027
#define IDC_RADIO_ANSWER1               1028
#define IDC_RADIO_ANSWER2               1029
#define IDC_RADIO_ANSWER3               1030
#define IDC_RADIO_ANSWER4               1031
#define IDC_RADIO_ANSWER5               1032
#define IDC_RADIO_ANSWER6               1033
#define IDC_RADIO_ANSWER7               1034
#define IDC_RADIO_ANSWER8               1035
#define IDC_EDIT_ANSWER1                1036
#define IDC_EDIT_ANSWER2                1037
#define IDC_EDIT_ANSWER3                1038
#define IDC_EDIT_ANSWER4                1039
#define IDC_EDIT_ANSWER5                1040
#define IDC_EDIT_ANSWER6                1041
#define IDC_EDIT_ANSWER7                1042
#define IDC_EDIT_ANSWER8                1043
#define IDC_BUTTON_SET1                 1044
#define IDC_BUTTON_SET2                 1045
#define IDC_BUTTON_SET3                 1046
#define IDC_BUTTON_SET4                 1047
#define IDC_BUTTON_SET5                 1048
#define IDC_BUTTON_SET6                 1049
#define IDC_BUTTON_SET7                 1050
#define IDC_BUTTON_SET8                 1051
#define IDC_BUTTON_AUTO                 1052
#define IDC_RADIO_TRUE                  1053
#define IDC_RADIO_FALSE                 1054
#define IDC_BUTTON_MARK                 1055
#define IDC_BUTTON_SAVE                 1056
#define IDC_STATIC_QUESTIONTYPE         1080
#define IDC_EDIT_ANSWER                 1081
#define IDC_STATIC_GROUP2               1082
#define IDC_CUSTOM_ITEM                 1083
#define IDC_EDIT_PAPERNAME              1090
#define IDC_EDIT_PAPERPATH              1091
#define IDC_EDIT_PAPERINFO              1092
#define IDC_EDIT_CANEDIT                1093
#define IDC_EDIT_TYPE                   1094
#define IDC_EDIT_PARENT                 1095
#define IDC_EDIT_ITEMCOUNT              1096
#define IDC_EDIT_FILETYPE               1097
#define IDC_EDIT_QNUMBER                1098
#define IDC_COMBO_CODE                  1100
#define IDC_COMBO_PAPERPATH             1110
#define IDC_COMBO_CUSTOMTYPE1           1111
#define IDC_EDIT_SCHCOUNT               1112
#define IDC_EDIT_MCHCOUNT               1113
#define IDC_EDIT_JDGCOUNT               1114
#define IDC_EDIT_BLKCOUNT               1115
#define IDC_EDIT_TXTCOUNT               1116
#define IDC_EDIT_GRPCOUNT               1117
#define IDC_EDIT_CUSTCOUNT              1118
#define IDC_STATIC_SCHCOUNT             1119
#define IDC_STATIC_MCHCOUNT             1120
#define IDC_STATIC_JDGCOUNT             1121
#define IDC_STATIC_BLKCOUNT             1122
#define IDC_STATIC_TXTCOUNT             1123
#define IDC_STATIC_GRPCOUNT             1124
#define IDC_STATIC_CUSTCOUNT            1125
#define IDC_EDIT_HOUR                   1126
#define IDC_EDIT_MINUTE                 1127
#define IDC_EDIT_FULLMARK               1128
#define IDC_RADIO_EQU                   1129
#define IDC_RADIO_DIF                   1130
#define IDC_COMBO_CUSTOMTYPE2           1131
#define IDC_EDIT_SCHPOINT               1132
#define IDC_EDIT_MCHPOINT               1133
#define IDC_EDIT_JDGPOINT               1134
#define IDC_EDIT_BLKPOINT               1135
#define IDC_EDIT_TXTPOINT               1136
#define IDC_EDIT_CUSTPOINT              1137
#define IDC_CHECK_USESTORE              1138
#define IDC_CHECK_QNUMORDER             1139
#define IDC_CHECK_SCHASMCH              1150
#define IDC_CHECK_MCHASSCH              1151
#define IDC_CHECK_MCHHALF               1152
#define IDC_CHECK_MCHNOSINGLE           1153
#define IDC_CHECK_RANDOM                1154
#define IDC_PROGRESS_TIME               1160
#define IDC_STATIC_INFO                 1161
#define IDC_STATIC_POS                  1162
#define IDC_CHECK_QLIST                 1164
#define IDC_BUTTON_HANDIN               1165
#define IDC_CHECK_SHOWSINGLE            1166
#define IDC_CHECK_ONLYFALSE             1170
#define IDC_BUTTON_OPTION               1180
#define IDC_CHECK_HOLESHOW              1181
#define IDC_LIST_TYPECHOOSE             1190
#define IDC_STATIC_SHOW                 1200
#define IDC_STATIC_BUTTON               1201
#define IDC_EDIT_INTER                  1202
#define IDC_STATIC_TYPE                 1203
#define IDC_CHECK_SHOWTYPE              1204
#define IDC_STATIC_GROUP3               1205
#define IDC_EDIT_ALLBUILDTIPS           1210
#define IDC_COMBO_TYPE                  1211
#define IDC_CHECK_AUTOSKIP              1212
#define IDC_CHECK_HANDLEINDEX           1213
#define IDC_CHECK_NUMSEP                1214
#define IDC_CHECK_DETECTASWINQ          1215
#define IDC_CHECK_DETECTASWAFTERQ       1216
#define IDC_STATIC_TITLE                1220
#define IDC_TAB                         1221
#define IDC_LIST_BLANKS                 1230
#define IDC_BUTTON_ADD                  1231
#define IDC_BUTTON_EDIT                 1232
#define IDC_BUTTON_DELWITHASW           1233
#define IDC_BUTTON_DELNOASW             1234
#define IDC_BUTTON_ASW                  1240
#define IDC_EDIT_SHOW                   1241
#define IDC_CHECK_BLKALLRIGHT           1250
#define IDC_CHECK_TXTALLRIGHT           1251
#define IDC_CHECK_ONLYBLK               1252
#define IDC_CHECK_RANDOMBLK             1253
#define IDC_EDIT_TXTSCORE               1260
#define IDC_STATIC_TXTSCORE             1261
#define IDC_STATIC_SIMILAR              1262
#define IDC_STATIC_BLKSCORE             1263
#define IDC_CUSTOM_REAL                 1264
#define IDC_CUSTOM_USER                 1265
#define IDC_BUTTON_ANSWER               1280
#define IDC_EDIT_OLDPSWD                1290
#define IDC_EDIT_NEWPSWD                1291
#define IDC_EDIT_CHECKPSWD              1292
#define IDC_EDIT_PASSWORD               1293
#define IDC_RADIO_ASTEXT                1300
#define IDC_RADIO_NEWCUSTOM             1301
#define IDC_RADIO_INCUSTOM              1302
#define IDC_COMBO_CUSTOMTYPE            1303
#define IDC_EDIT_ITEMGRPNAME            1310
#define IDC_LIST_GROUP                  1311
#define IDC_BUTTON_UP                   1312
#define IDC_BUTTON_DOWN                 1313
#define IDC_BUTTON_PASTE                1314
#define IDC_BUTTON_NEWG                 1315
#define IDC_BUTTON_DELG                 1316
#define IDC_BUTTON_COPY                 1317
#define IDC_EDIT_SUMMARYLEN             1320
#define IDC_RADIO_STOM                  1330
#define IDC_RADIO_MTOS                  1331
#define IDC_RADIO_SELDUPLICATE          1332
#define IDC_EDIT_SIMILAR                1333
#define IDC_RADIO_CTOJ                  1334
#define IDC_RADIO_NO                    1340
#define IDC_RADIO_DEFAULT               1341
#define IDC_RADIO_USER                  1342
#define IDC_EDIT_TITLE                  1343
#define IDC_EDIT_WIDTH                  1344
#define IDC_EDIT_HEIGHT                 1345
#define IDC_STATIC_COLOR                1346
#define IDC_STATIC_BKCOLOR              1346
#define IDC_STATIC_TXTCOLOR             1347
#define IDC_EDIT_QUALITY                1348
#define IDC_EDIT_JPEGCHOOSE             1349
#define IDC_BUTTON_OPEN                 1350
#define IDC_BUTTON_VIEW                 1351
#define IDC_BUTTON_SET                  1352
#define IDC_COMBO_FONTSIZE              1360
#define IDC_LIST_TXTOUT                 1370
#define IDC_EDIT_FILEPATH               1372
#define IDC_BUTTON_FILEPATH             1373
#define IDC_RADIO_ONLYASW               1374
#define IDC_RADIO_WITHQ                 1375
#define IDC_CHECK_WITHRES               1376
#define IDC_COMBO_ANSIFONT              1377
#define IDC_COMBO_MAINFONT              1378
#define IDC_COMBO_PREFACEFONT           1379
#define IDC_RADIO_ONLYQ                 1381
#define IDC_RADIO_WITHASW               1382
#define IDC_RADIO_ALL                   1383
#define IDS_LIST_INDEX                  10000
#define IDS_LIST_TYPE                   10001
#define IDS_LIST_SUMMARY                10002
#define IDS_ITEMCOUNT                   10010
#define IDS_ITEMCOUNTFORMAT             10011
#define IDS_ITEMTYPE_SCH                10014
#define IDS_ITEMTYPE_MCH                10015
#define IDS_ITEMTYPE_JDG                10016
#define IDS_ITEMTYPE_BLK                10017
#define IDS_ITEMTYPE_TXT                10018
#define IDS_ITEMTYPE_GRP                10019
#define IDS_ITEMTYPE_CUSTOM             10020
#define IDS_MSGCAPTION_INFOR            10021
#define IDS_MSGCAPTION_WARNING          10022
#define IDS_MSGCAPTION_ERROR            10023
#define IDS_MSGCAPTION_ASK              10024
#define IDS_MSGCAPTION_RESULT           10025
#define IDS_MSGINFO_TIME                10026
#define IDS_MSGINFO_ERROR               10027
#define IDS_MAIN_QUIT                   10030
#define IDS_MAIN_RESET                  10031
#define IDS_MAIN_LIBRARYVIEW            10032
#define IDS_QVIEW_FINDFAIL              10040
#define IDS_QVIEW_MENUSTORE             10041
#define IDS_QVIEW_BUTTONUNSTORE         10042
#define IDS_QVIEW_BUTTONSTORE           10043
#define IDS_QVIEW_MENUUNSTORE           10045
#define IDS_QVIEW_DELASK                10046
#define IDS_QVIEW_FINDCUSTEOM           10047
#define IDS_DOC_INITPAPERFAIL           10050
#define IDS_DOC_OPENFAIL                10051
#define IDS_DOC_OPENFILECAPTION         10052
#define IDS_DOC_SAVEFAIL                10053
#define IDS_DOC_SAVEFILECAPTION         10054
#define IDS_DOC_CLOSEASKNOSAVE          10055
#define IDS_DOC_CLOSEASKMODIFY          10056
#define IDS_DOC_CLOSEASKNEW             10057
#define IDS_DOC_PASTEFAIL               10058
#define IDS_DOC_LOADSTORECAPTION        10059
#define IDS_DOC_UNSTOREASK              10060
#define IDS_DOC_ADDTYPEFAIL             10061
#define IDS_DOC_DELTYPEFAIL             10062
#define IDS_DOC_SAVEFILEFILTER          10063
#define IDS_DOC_LOADFILEFILTER          10064
#define IDS_DOC_LOADSTOREFILTER         10065
#define IDS_DOC_CLEARMRU                10066
#define IDS_DOC_95SAVEFILEFILTER        10067
#define IDS_DOC_SAVEFILEFILTERNC        10068
#define IDS_DOC_95LOADFILEFILTER        10069
#define IDS_DOC_OPENINCOMPLETE          10070
#define IDS_DOC_WIN95XML                10071
#define IDS_DOC_MAXCOMPATIBLE           10072
#define IDS_EDITDLG_NOANSWER            10080
#define IDS_EDITDLG_NOSAVE              10081
#define IDS_EDITDLG_TITLENEW            10082
#define IDS_EDITDLG_TITLEEDIT           10083
#define IDS_EDITDLG_INFONEW             10084
#define IDS_EDITDLG_INFOREVIEW          10085
#define IDS_EDITDLG_NODESC              10086
#define IDS_EDITDLG_ALLBUILDNULL        10087
#define IDS_EDITDLG_ALLBUILDALLASW      10088
#define IDS_EDITDLG_ALLBUILDNOASW       10089
#define IDS_EDITDLG_ALLBUILDPARTASW     10090
#define IDS_EDITDLG_ALLBUILDNOTALL      10091
#define IDS_EDITDLG_ALLBUILDSHOWSEL     10092
#define IDS_EDITDLG_ALLBUILDTIPS1       10093
#define IDS_EDITDLG_ALLBUILDTIPS        10093
#define IDS_EDITDLG_ALLBUILDTIPS2       10094
#define IDS_EDITDLG_CANNOTALLBUILD      10094
#define IDS_EDITDLG_DELASK              10096
#define IDS_EDITDLGC_ONLYOPTION         10100
#define IDS_EDITDLGC_INVALID            10101
#define IDS_EDITFRM_TITLE               10110
#define IDS_EDITFRM_INITFAIL            10111
#define IDS_EDITFRM_CREATEFAIL          10112
#define IDS_EDITFRM_FINDFAIL            10113
#define IDS_EDITFRM_REPLACEDONE         10114
#define IDS_EDITFRM_DROPMULTIFILES      10115
#define IDS_EDITFRM_CLOSEASK            10116
#define IDS_EDITFRM_GROUPTITLE          10117
#define IDS_EDITFRM_CLOSEASKNEW         10118
#define IDS_EDITFRM_LOADFILTER          10119
#define IDS_EDITFRM_SAVEFILTER          10120
#define IDS_EDITFRM_READFAIL            10121
#define IDS_EDITFRM_SAVEFAIL            10122
#define IDS_TESTSET_TIMETOOSHORT        10130
#define IDS_TESTSET_TIMETOOLONG         10131
#define IDS_TESTSET_CONFLICT            10132
#define IDS_TESTSET_COMMSET             10133
#define IDS_TESTSET_CHSSET              10134
#define IDS_TESTSET_BLKTXTSET           10135
#define IDS_TESTFRAME_TITLE             10140
#define IDS_TESTFRAME_CANCEL            10141
#define IDS_TESTFRAME_NOTALLDONEASK     10142
#define IDS_TESTFRAME_DONEASK           10143
#define IDS_TESTFRAME_BLKTXT            10144
#define IDS_LISTFRM_TITLE               10150
#define IDS_QLIST_INDEX                 10160
#define IDS_QLIST_STATE                 10161
#define IDS_QLIST_TYPE                  10162
#define IDS_QLIST_ABSTRACT              10163
#define IDS_QLIST_STORED                10164
#define IDS_QLIST_UNASW                 10165
#define IDS_QLIST_MARK                  10166
#define IDS_QLIST_WRONG                 10167
#define IDS_QLIST_HALFRIGHT             10168
#define IDS_QLIST_ALLRIGHT              10169
#define IDS_QLIST_NOSET                 10170
#define IDS_QUIZMKR_ATTENTION           10180
#define IDS_QUIZMKR_TIMEPOINT           10181
#define IDS_QUIZMKR_TYPEINFO            10182
#define IDS_QUIZMKR_BLKINFO             10183
#define IDS_QUIZMKR_NOSCOREINFO         10184
#define IDS_QUIZMKR_POINT               10185
#define IDS_QUIZMKR_ANSWER              10186
#define IDS_QUIZMKR_ASWTXT              10186
#define IDS_QUIZMKR_PAPEREND            10187
#define IDS_QUIZMKR_RESTXT              10187
#define IDS_TESTCOMP_START              10200
#define IDS_TESTCOMP_STOP               10201
#define IDS_TESTCOMP_CHECK              10202
#define IDS_TESTCOMP_CHECKDIF           10203
#define IDS_TESTCOMP_CONTINUE           10204
#define IDS_TESTVIEW_TITLE              10210
#define IDS_TESTVIEW_STOREALL           10211
#define IDS_ABOUTDLG_CODE               10220
#define IDS_ABOUTDLG_DATE               10221
#define IDS_DOCDLG_INFO                 10230
#define IDS_LVIEW_INFO                  10240
#define IDS_LVIEW_ASKDELTYPE            10241
#define IDS_LVIEW_OPENEXPLRFAIL         10242
#define IDS_LVIEW_READONLY              10243
#define IDS_LVIEW_LOCKXMLCAUTION        10244
#define IDS_LVIEW_SETCOVERFAIL          10245
#define IDS_BLKDLG_INDEX                10250
#define IDS_BLKDLG_START                10251
#define IDS_BLKDLG_END                  10252
#define IDS_BLKDLG_ASW                  10253
#define IDS_BLKDLG_SWITCHPAGE           10254
#define IDS_BLKDLG_NOSEL                10255
#define IDS_BLKDLG_DELASK               10256
#define IDS_BLKDLG_EDITASK              10257
#define IDS_BLKDLG_ERRREACHMAX          10258
#define IDS_BLKDLG_ERRNODESC            10259
#define IDS_BLKDLG_ERRRANGECONF         10260
#define IDS_BLKDLG_ERRALLOCFAIL         10261
#define IDS_BLKDLG_ERRNOASW             10262
#define IDS_BLKDLG_ERREDITOVER          10263
#define IDS_BLKDLG_ERRTRANSCODEFAIL     10264
#define IDS_BLKDLG_NOBLOCKS             10265
#define IDS_EDITDLGT_NOASW              10280
#define IDS_PSWDDLG_OLDPSWDF            10290
#define IDS_PSWDDLG_NEWPSWDIN           10291
#define IDS_PSWDDLG_DELPSWD             10292
#define IDS_PSWDDLG_WRONG               10293
#define IDS_PSWDDLG_TOOSHORT            10294
#define IDS_TYPEDLG_TYPE                10300
#define IDS_TYPEDLG_COUNT               10301
#define IDS_ITEMGRPDLG_IDX              10310
#define IDS_ITEMGRPDLG_TYPE             10311
#define IDS_ITEMGRPDLG_DESC             10312
#define IDS_GROUPDLG_DELASK             10320
#define IDS_GROUPDLG_DELGASK            10321
#define IDS_GROUPDLG_NOITEM             10322
#define IDS_GROUPDLG_NOSAVE             10323
#define IDS_GROUPDLG_INFOVIEW           10324
#define IDS_CHECKDLG_MISS               10330
#define IDS_BATCHSETDLG_SELDUPY         10340
#define IDS_BATCHSETDLG_SELDUPN         10341
#define IDS_JPEGCOVERDLG_OPENTITLE      10350
#define IDS_JPEGCOVERDLG_OPENFILTER     10351
#define IDS_JPEGCOVERDLG_OPENFAIL       10352
#define IDS_JPEGCOVERDLG_NOTITLE        10353
#define IDS_JPEGCOVERDLG_NOPATH         10354
#define IDS_VIEWDLG_FINDFAIL            10360
#define IDS_VIEWDLG_BUTTONSTORE         10361
#define IDS_TEST_TESTSET                10370
#define IDS_TEST_CREATETESTFAIL         10371
#define IDS_TEST_BEGINTESTASK           10372
#define IDS_TEST_SHOWSCORE              10373
#define IDS_TEST_RETESTASK              10374
#define IDS_TEST_PAPERSET               10375
#define IDS_TEST_GROUPCAUTIONM          10376
#define IDS_TEST_GROUPCAUTIONS          10377
#define IDS_IMGFRM_COVERVIEW            10380
#define IDS_IMGFRM_NOIMAGE              10381
#define IDS_IMGFRM_LOADFILTER           10382
#define IDS_IMGFRM_LOADTITLE            10383
#define IDS_IMGFRM_DELASK               10384
#define IDS_IMGFRM_INVALIDIMG           10385
#define IDS_IMGFRM_TITLE                10386
#define IDS_IMGFRM_ITEMIMAGE            10387
#define IDS_IMGFRM_READFAIL             10388
#define IDS_IMGFRM_TOOBIG               10389
#define IDS_TESTBAR_MARK                10400
#define IDS_TESTBAR_UNMARK              10401
#define IDS_TESTBAR_TIMELEFT_H          10402
#define IDS_TESTBAR_TIMELEFT_M          10403
#define IDS_TESTBAR_TIMELEFT_S          10404
#define IDS_TESTBAR_NOTIMELMT           10405
#define IDS_TESTBAR_TIMEOUT             10406
#define IDS_TXTOUTDLG_TXTONLY           10410
#define IDS_TXTOUTDLG_HTMLPLUS          10411
#define IDS_TXTOUTDLG_HTMLONLY          10412
#define IDS_TXTOUTDLG_SAVEPATH          10413
#define IDS_TXTOUTDLG_TXTFILTER         10414
#define IDS_TXTOUTDLG_HTMLFILTER        10415
#define IDS_TXTOUTDLG_SAVEFAIL          10416
#define IDS_SHOWWND_JPEGFILTER          10430
#define IDS_SHOWWND_BMPFILTER           10431
#define IDS_SHOWWND_PNGFILTER           10432
#define IDS_SHOWWND_SAVETITLE           10433
#define IDS_TYPEPROPT_DUPL              10440
#define IDS_TYPEPROPT_DEFAULT           10441
#define IDS_ITEM_YES                    20000
#define IDS_ITEM_NO                     20001
#define IDS_ITEM_CORRECT                20002
#define IDS_ITEM_INCORRECT              20003
#define IDS_ITEM_RESOLVE                20004
#define IDS_ITEM_IMAGETITLE             20005
#define IDS_ITEM_BLANKSAMPLE            20006
#define IDS_ITEM_TEXTASW                20007
#define IDS_ITEM_USERASW                20008
#define IDS_ITEM_SCORE                  20009
#define IDS_PAPER_DEFAULTDESC           20020
#define IDS_PAPER_STORELIST             20021
#define IDS_PAPER_NOPATH                20022
#define IDS_PAPER_ITEMCOUNT             20023
#define IDS_PAPER_TYPEINFO              20024
#define IDS_PAPER_BIN                   20025
#define IDS_PAPER_OLDBIN                20026
#define IDS_PAPER_XML                   20027
#define IDS_PAPER_UNKNOWN               20028
#define IDS_TMPLIST_SCHCOUNT            20030
#define IDS_TMPLIST_MCHCOUNT            20031
#define IDS_TMPLIST_JDGCOUNT            20032
#define IDS_TMPLIST_BLKCOUNT            20033
#define IDS_TMPLIST_TXTCOUNT            20034
#define IDS_PROPS_STORE                 20040
#define IDS_PROPS_NOPARENT              20041
#define IDS_VERCHK_ASK1                 20050
#define IDS_VERCHK_ASK2                 20051
#define IDS_VERCHK_VER1                 20052
#define ID_FILE_SAVE_ALL                32771
#define ID_FILE_CLEARMRU                32772
#define ID_EDIT_FINDNEXT                32781
#define ID_EDIT_PROPERTIES              32782
#define ID_EDIT_COPYEX                  32783
#define ID_PAPER_EDITABLE               32791
#define ID_PAPER_LOCK                   32792
#define ID_PAPER_NEWQUESTION            32793
#define ID_PAPER_STORE                  32794
#define ID_PAPER_LOADSTORE              32795
#define ID_PAPER_EDITOBJECT             32796
#define ID_PAPER_COVERSET               32797
#define ID_PAPER_BATCHSET               32798
#define ID_PAPER_NEWGROUP               32799
#define ID_PAPER_NEWTYPE                32800
#define ID_PAPER_DELTYPE                32801
#define ID_PAPER_EDITGROUP              32802
#define ID_PAPER_OPENINEXPLORER         32803
#define ID_EX_EXIT                      32821
#define ID_EX_AUTOSEP                   32822
#define ID_EX_FONT                      32823
#define ID_TEST_BEGIN                   32831
#define ID_TEST_VIEW                    32832
#define ID_TEST_MAKE                    32833
#define ID_TEST_COMPETITIVE             32834
#define ID_VIEW_COLORNORMAL             32901
#define ID_VIEW_COLORGREEN              32902
#define ID_VIEW_COLORDARK               32903
#define ID_VIEW_RESET                   32904
#define ID_VIEW_SAMMARYLEN              32905
#define ID_SHOW_SAVEIMG                 32911

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        192
#define _APS_NEXT_COMMAND_VALUE         32913
#define _APS_NEXT_CONTROL_VALUE         1384
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
